// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grader.proto

package grader

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubmitForGradingRequest struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitForGradingRequest) Reset()         { *m = SubmitForGradingRequest{} }
func (m *SubmitForGradingRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitForGradingRequest) ProtoMessage()    {}
func (*SubmitForGradingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcfa04c851659cab, []int{0}
}

func (m *SubmitForGradingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitForGradingRequest.Unmarshal(m, b)
}
func (m *SubmitForGradingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitForGradingRequest.Marshal(b, m, deterministic)
}
func (m *SubmitForGradingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitForGradingRequest.Merge(m, src)
}
func (m *SubmitForGradingRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitForGradingRequest.Size(m)
}
func (m *SubmitForGradingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitForGradingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitForGradingRequest proto.InternalMessageInfo

func (m *SubmitForGradingRequest) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Task struct {
	AssignmentId string `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	TestKey      string `protobuf:"bytes,2,opt,name=test_key,json=testKey,proto3" json:"test_key,omitempty"`
	ZipKey       string `protobuf:"bytes,3,opt,name=zip_key,json=zipKey,proto3" json:"zip_key,omitempty"`
	StudentName  string `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	// Timeout is in seconds.
	Timeout              int32    `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CallbackUri          string   `protobuf:"bytes,6,opt,name=callback_uri,json=callbackUri,proto3" json:"callback_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcfa04c851659cab, []int{1}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetAssignmentId() string {
	if m != nil {
		return m.AssignmentId
	}
	return ""
}

func (m *Task) GetTestKey() string {
	if m != nil {
		return m.TestKey
	}
	return ""
}

func (m *Task) GetZipKey() string {
	if m != nil {
		return m.ZipKey
	}
	return ""
}

func (m *Task) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *Task) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Task) GetCallbackUri() string {
	if m != nil {
		return m.CallbackUri
	}
	return ""
}

type SubmitForGradingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitForGradingResponse) Reset()         { *m = SubmitForGradingResponse{} }
func (m *SubmitForGradingResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitForGradingResponse) ProtoMessage()    {}
func (*SubmitForGradingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcfa04c851659cab, []int{2}
}

func (m *SubmitForGradingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitForGradingResponse.Unmarshal(m, b)
}
func (m *SubmitForGradingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitForGradingResponse.Marshal(b, m, deterministic)
}
func (m *SubmitForGradingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitForGradingResponse.Merge(m, src)
}
func (m *SubmitForGradingResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitForGradingResponse.Size(m)
}
func (m *SubmitForGradingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitForGradingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitForGradingResponse proto.InternalMessageInfo

type CreateAssignmentRequest struct {
	ImageName            string   `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageTar             []byte   `protobuf:"bytes,2,opt,name=image_tar,json=imageTar,proto3" json:"image_tar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAssignmentRequest) Reset()         { *m = CreateAssignmentRequest{} }
func (m *CreateAssignmentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAssignmentRequest) ProtoMessage()    {}
func (*CreateAssignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcfa04c851659cab, []int{3}
}

func (m *CreateAssignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAssignmentRequest.Unmarshal(m, b)
}
func (m *CreateAssignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAssignmentRequest.Marshal(b, m, deterministic)
}
func (m *CreateAssignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAssignmentRequest.Merge(m, src)
}
func (m *CreateAssignmentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAssignmentRequest.Size(m)
}
func (m *CreateAssignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAssignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAssignmentRequest proto.InternalMessageInfo

func (m *CreateAssignmentRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *CreateAssignmentRequest) GetImageTar() []byte {
	if m != nil {
		return m.ImageTar
	}
	return nil
}

type CreateAssignmentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAssignmentResponse) Reset()         { *m = CreateAssignmentResponse{} }
func (m *CreateAssignmentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAssignmentResponse) ProtoMessage()    {}
func (*CreateAssignmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcfa04c851659cab, []int{4}
}

func (m *CreateAssignmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAssignmentResponse.Unmarshal(m, b)
}
func (m *CreateAssignmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAssignmentResponse.Marshal(b, m, deterministic)
}
func (m *CreateAssignmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAssignmentResponse.Merge(m, src)
}
func (m *CreateAssignmentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAssignmentResponse.Size(m)
}
func (m *CreateAssignmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAssignmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAssignmentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SubmitForGradingRequest)(nil), "grader.SubmitForGradingRequest")
	proto.RegisterType((*Task)(nil), "grader.Task")
	proto.RegisterType((*SubmitForGradingResponse)(nil), "grader.SubmitForGradingResponse")
	proto.RegisterType((*CreateAssignmentRequest)(nil), "grader.CreateAssignmentRequest")
	proto.RegisterType((*CreateAssignmentResponse)(nil), "grader.CreateAssignmentResponse")
}

func init() { proto.RegisterFile("grader.proto", fileDescriptor_fcfa04c851659cab) }

var fileDescriptor_fcfa04c851659cab = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x6a, 0x1b, 0x31,
	0x10, 0x45, 0x49, 0xbc, 0x4e, 0xc6, 0x5b, 0x30, 0x3a, 0xc4, 0xaa, 0xd3, 0xd2, 0x8d, 0x7a, 0x31,
	0x39, 0xc4, 0x90, 0xde, 0x02, 0x3d, 0x94, 0x42, 0x43, 0x29, 0xf4, 0xb0, 0x8d, 0xcf, 0xcb, 0xd8,
	0x2b, 0x16, 0xb1, 0x5e, 0x69, 0x2b, 0x69, 0xa1, 0xf6, 0xb1, 0xbf, 0xd0, 0x0f, 0xea, 0x47, 0xf4,
	0x17, 0xfa, 0x03, 0xfd, 0x83, 0xb2, 0x92, 0xd7, 0x06, 0x9b, 0x3d, 0xbe, 0xf7, 0x46, 0xf3, 0xe6,
	0x8d, 0x06, 0xe2, 0xc2, 0x60, 0x2e, 0xcc, 0x7d, 0x6d, 0xb4, 0xd3, 0x34, 0x0a, 0x68, 0xfa, 0xaa,
	0xd0, 0xba, 0x58, 0x8b, 0x39, 0xd6, 0x72, 0x8e, 0x4a, 0x69, 0x87, 0x4e, 0x6a, 0x65, 0x43, 0x15,
	0x7f, 0x0f, 0x93, 0x6f, 0xcd, 0xb2, 0x92, 0xee, 0x93, 0x36, 0x4f, 0x06, 0x73, 0xa9, 0x8a, 0x54,
	0x7c, 0x6f, 0x84, 0x75, 0x94, 0xc3, 0xc0, 0xa1, 0x2d, 0x2d, 0x23, 0xc9, 0xf9, 0x6c, 0xf4, 0x10,
	0xdf, 0xef, 0xda, 0x3f, 0xa3, 0x2d, 0xd3, 0x20, 0xf1, 0xdf, 0x04, 0x2e, 0x5a, 0x4c, 0xdf, 0xc2,
	0x0b, 0xb4, 0x56, 0x16, 0xaa, 0x12, 0xca, 0x65, 0x32, 0x67, 0x24, 0x21, 0xb3, 0xab, 0x34, 0x3e,
	0x90, 0x9f, 0x73, 0xfa, 0x12, 0x2e, 0x9d, 0xb0, 0x2e, 0x2b, 0xc5, 0x86, 0x9d, 0x79, 0x7d, 0xd8,
	0xe2, 0x2f, 0x62, 0x43, 0x27, 0x30, 0xdc, 0xca, 0xda, 0x2b, 0xe7, 0x5e, 0x89, 0xb6, 0xb2, 0x6e,
	0x85, 0x5b, 0x88, 0xad, 0x6b, 0xf2, 0xb6, 0xab, 0xc2, 0x4a, 0xb0, 0x0b, 0xaf, 0x8e, 0x76, 0xdc,
	0x57, 0xac, 0x04, 0x65, 0x30, 0x74, 0xb2, 0x12, 0xba, 0x71, 0x6c, 0x90, 0x90, 0xd9, 0x20, 0xed,
	0x60, 0xfb, 0x78, 0x85, 0xeb, 0xf5, 0x12, 0x57, 0x65, 0xd6, 0x18, 0xc9, 0xa2, 0xf0, 0xb8, 0xe3,
	0x16, 0x46, 0xf2, 0x29, 0xb0, 0xd3, 0x05, 0xd8, 0x5a, 0x2b, 0x2b, 0xf8, 0x02, 0x26, 0x1f, 0x8d,
	0x40, 0x27, 0x3e, 0xec, 0x53, 0x74, 0xcb, 0x79, 0x0d, 0x20, 0x2b, 0x2c, 0x44, 0x18, 0x2a, 0x84,
	0xbd, 0xf2, 0x8c, 0x1f, 0xe9, 0x06, 0x02, 0xc8, 0x1c, 0x1a, 0x1f, 0x35, 0x4e, 0x2f, 0x3d, 0xf1,
	0x8c, 0xa6, 0xb5, 0x3c, 0x6d, 0x1b, 0x2c, 0x1f, 0xfe, 0x11, 0x88, 0x9e, 0xfc, 0x9e, 0x69, 0x05,
	0xe3, 0xe3, 0xc9, 0xe8, 0x9b, 0xee, 0x13, 0x7a, 0x3e, 0x6d, 0x9a, 0xf4, 0x17, 0xec, 0x42, 0x5d,
	0xff, 0xfc, 0xf3, 0xf7, 0xd7, 0xd9, 0x98, 0x8f, 0xfc, 0x45, 0x58, 0x5f, 0xf6, 0x48, 0xee, 0xe8,
	0x0f, 0x18, 0x1f, 0x4f, 0x75, 0xb0, 0xeb, 0x59, 0xc3, 0xc1, 0xae, 0x2f, 0x10, 0xbf, 0xf5, 0x76,
	0x37, 0xfc, 0x3a, 0x1c, 0xe0, 0xbe, 0x60, 0xbe, 0xf2, 0x2f, 0x1e, 0xc9, 0xdd, 0x32, 0xf2, 0xa7,
	0xf8, 0xee, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x8c, 0xcb, 0xa0, 0xc0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GraderClient is the client API for Grader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GraderClient interface {
	// SubmitForGrading provides an endpoint for allowing caller to submit a student's name
	// and assignment information for grading.
	//
	// This is a non-blocking call, it returns a "OK" as acknowledgement or "InvalidArgument"
	// for invalid parameters.
	//
	// Once the assignment has been graded, it will call a specific endpoint of the caller.
	SubmitForGrading(ctx context.Context, in *SubmitForGradingRequest, opts ...grpc.CallOption) (*SubmitForGradingResponse, error)
	// CreateAssignment creates an assignment with a given dockerfile and startup script.
	//
	// This endpoint creates an image on the docker host and returns an unique assignment ID.
	//
	// Calling this endpoint is REQUIRED before grading any assignments.
	CreateAssignment(ctx context.Context, in *CreateAssignmentRequest, opts ...grpc.CallOption) (*CreateAssignmentResponse, error)
}

type graderClient struct {
	cc *grpc.ClientConn
}

func NewGraderClient(cc *grpc.ClientConn) GraderClient {
	return &graderClient{cc}
}

func (c *graderClient) SubmitForGrading(ctx context.Context, in *SubmitForGradingRequest, opts ...grpc.CallOption) (*SubmitForGradingResponse, error) {
	out := new(SubmitForGradingResponse)
	err := c.cc.Invoke(ctx, "/grader.Grader/SubmitForGrading", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graderClient) CreateAssignment(ctx context.Context, in *CreateAssignmentRequest, opts ...grpc.CallOption) (*CreateAssignmentResponse, error) {
	out := new(CreateAssignmentResponse)
	err := c.cc.Invoke(ctx, "/grader.Grader/CreateAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraderServer is the server API for Grader service.
type GraderServer interface {
	// SubmitForGrading provides an endpoint for allowing caller to submit a student's name
	// and assignment information for grading.
	//
	// This is a non-blocking call, it returns a "OK" as acknowledgement or "InvalidArgument"
	// for invalid parameters.
	//
	// Once the assignment has been graded, it will call a specific endpoint of the caller.
	SubmitForGrading(context.Context, *SubmitForGradingRequest) (*SubmitForGradingResponse, error)
	// CreateAssignment creates an assignment with a given dockerfile and startup script.
	//
	// This endpoint creates an image on the docker host and returns an unique assignment ID.
	//
	// Calling this endpoint is REQUIRED before grading any assignments.
	CreateAssignment(context.Context, *CreateAssignmentRequest) (*CreateAssignmentResponse, error)
}

// UnimplementedGraderServer can be embedded to have forward compatible implementations.
type UnimplementedGraderServer struct {
}

func (*UnimplementedGraderServer) SubmitForGrading(ctx context.Context, req *SubmitForGradingRequest) (*SubmitForGradingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitForGrading not implemented")
}
func (*UnimplementedGraderServer) CreateAssignment(ctx context.Context, req *CreateAssignmentRequest) (*CreateAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAssignment not implemented")
}

func RegisterGraderServer(s *grpc.Server, srv GraderServer) {
	s.RegisterService(&_Grader_serviceDesc, srv)
}

func _Grader_SubmitForGrading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitForGradingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServer).SubmitForGrading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grader.Grader/SubmitForGrading",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServer).SubmitForGrading(ctx, req.(*SubmitForGradingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grader_CreateAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraderServer).CreateAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grader.Grader/CreateAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraderServer).CreateAssignment(ctx, req.(*CreateAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grader.Grader",
	HandlerType: (*GraderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitForGrading",
			Handler:    _Grader_SubmitForGrading_Handler,
		},
		{
			MethodName: "CreateAssignment",
			Handler:    _Grader_CreateAssignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grader.proto",
}
